// Copyright © SixtyFPS GmbH <info@slint.dev>
// SPDX-License-Identifier: GPL-3.0-only OR LicenseRef-Slint-Royalty-free-2.0 OR LicenseRef-Slint-Software-3.0

import { Fluent2FontSettings, Fluent2Palette, Fluent2SizeSettings, Icons } from "styling.slint";
import { FocusBorder } from "components.slint";
import { FocusTouchArea } from "internal-components.slint";

export component CheckBox {
    in property <string> text;
    in property <bool> enabled: true;
    out property <bool> has-focus: touch-area.has-focus;
    in-out property <bool> checked;

    callback toggled;

    private property <color> text-color: Fluent2Palette.checkbox-foreground;

    min-height: max(Fluent2SizeSettings.checkbox-size, layout.min-height);
    accessible-checkable: true;
    accessible-enabled: root.enabled;
    accessible-label: root.text;
    accessible-checked <=> root.checked;
    accessible-role: checkbox;
    accessible-action-default => {
        if (root.enabled) {
           root.checked = !root.checked;
           root.toggled();
        }
    }
    forward-focus: touch-area;

    states [
        disabled when !root.enabled : {
            border.border-color: Fluent2Palette.checkbox-disabled-border;
            background.background: root.checked ? Fluent2Palette.checkbox-checked-disabled-background : Fluent2Palette.checkbox-disabled-background;
            icon.colorize: Fluent2Palette.checkbox-checkmark-disabled-foreground;
            root.text-color: Fluent2Palette.checkbox-disabled-foreground;
        }
        pressed when touch-area.pressed : {
            border.border-color: Fluent2Palette.checkbox-disabled-border;
            background.background: root.checked ? Fluent2Palette.checkbox-checked-pressed-background : Fluent2Palette.checkbox-pressed-background;
            icon.colorize: Fluent2Palette.checkbox-checkmark-pressed-foreground;
        }
        hover when touch-area.has-hover : {
            background.background: root.checked ?  Fluent2Palette.checkbox-checked-hover-background : Fluent2Palette.checkbox-hover-background;
        }
        checked when root.checked && root.enabled : {
            background.background: Fluent2Palette.checkbox-checked-background;
        }
    ]

    animate text-color { duration: Fluent2SizeSettings.checkbox-motion-duration; }

    layout := HorizontalLayout {
        spacing: Fluent2SizeSettings.checkbox-label-spacing;

        background := Rectangle {
            width: Fluent2SizeSettings.checkbox-size;
            height: self.width;
            y: (parent.height - self.height) / 2;
            background: Fluent2Palette.checkbox-background;
            border-radius: Fluent2SizeSettings.checkbox-radius;

            animate background { duration: Fluent2SizeSettings.checkbox-motion-duration; }

            border := Rectangle {
                border-color: Fluent2Palette.checkbox-border;
                border-width: root.checked ? Fluent2SizeSettings.control-hidden-stroke-width : Fluent2SizeSettings.checkbox-border-width;
                border-radius: parent.border-radius;

                animate border-color { duration: Fluent2SizeSettings.checkbox-motion-duration; }
            }

            icon := Image {
                image-fit: contain;
                visible: root.checked;
                source: Icons.check-mark;
                colorize: Fluent2Palette.checkbox-checkmark-foreground;
                width: Fluent2SizeSettings.checkbox-checkmark-size;
                accessible-role: none;

                animate colorize { duration: Fluent2SizeSettings.checkbox-motion-duration; }
            }
        }

        if root.text != "" : Text {
            text: root.text;
            color: root.text-color;
            font-size: Fluent2FontSettings.body.font-size;
            font-weight: Fluent2FontSettings.body.font-weight;
            font-family: Fluent2Palette.font-family;
            vertical-alignment: center;
            horizontal-alignment: left;
        }
    }

    touch-area := FocusTouchArea {
        enabled: root.enabled;

        clicked => {
            if (root.enabled) {
                root.checked = !root.checked;
                root.toggled();
            }
        }
    }

    // focus border
    if root.has-focus && root.enabled : FocusBorder {
        border-radius: Fluent2SizeSettings.checkbox-focus-radius;
    }
}
