// Copyright © SixtyFPS GmbH <info@slint.dev>
// SPDX-License-Identifier: GPL-3.0-only OR LicenseRef-Slint-Royalty-free-2.0 OR LicenseRef-Slint-Software-3.0

import { Fluent2FontSettings, Fluent2Palette, Fluent2SizeSettings } from "styling.slint";

export component GroupBox {
    in property <string> title;
    in property <bool> enabled: true;
    in property <length> content-padding;

    accessible-role: groupbox;
    accessible-label: root.title;
    accessible-enabled: root.enabled;

    VerticalLayout {
        spacing: Fluent2SizeSettings.group-title-spacing;
        padding-top: Fluent2SizeSettings.group-top-padding;
        padding-bottom: Fluent2SizeSettings.group-bottom-padding;

        if root.title != "" : Text {
            vertical-stretch: 0;
            color: !root.enabled ? Fluent2Palette.text-disabled : Fluent2Palette.control-foreground;
            font-size: Fluent2FontSettings.body-strong.font-size;
            font-weight: Fluent2FontSettings.body-strong.font-weight;
            font-family: Fluent2Palette.font-family;
            text: root.title;
        }

        Rectangle {
            vertical-stretch: 1;

            GridLayout {
                padding: root.content-padding;

                @children
            }
        }
    }
}
