// Copyright © SixtyFPS GmbH <info@slint.dev>
// SPDX-License-Identifier: GPL-3.0-only OR LicenseRef-Slint-Royalty-free-2.0 OR LicenseRef-Slint-Software-3.0

import { Fluent2FontSettings, Fluent2Palette, Fluent2SizeSettings } from "styling.slint";
import { LineEditBase, LineEditClearIcon, LineEditPasswordIcon } from "lineedit-base.slint";

export component LineEdit {
    in property <bool> enabled <=> base.enabled;
    in property <InputType> input-type;
    in property <TextHorizontalAlignment> horizontal-alignment <=> base.horizontal-alignment;
    in property <bool> read-only <=> base.read-only;
    in property <length> font-size <=> base.font-size;
    in property <string> font-family <=> base.font-family;
    in property <bool> font-italic <=> base.font-italic;
    in property <string> placeholder-text <=> base.placeholder-text;
    out property <bool> has-focus <=> base.has-focus;
    in-out property <string> text <=> base.text;

    callback accepted <=> base.accepted;
    callback edited <=> base.edited;
    callback key-pressed <=> base.key-pressed;
    callback key-released <=> base.key-released;
    accessible-role: text-input;
    accessible-enabled: root.enabled;
    accessible-value <=> text;
    accessible-placeholder-text: placeholder-text;
    accessible-read-only: root.read-only;
    accessible-action-set-value(v) => { text = v; edited(v); }

    public function set-selection-offsets(start: int, end: int) {
        base.set-selection-offsets(start, end);
    }

    public function select-all() {
        base.select-all();
    }

    public function clear-selection() {
        base.clear-selection();
    }

    public function cut() {
        base.cut();
    }

    public function copy() {
        base.copy();
    }

    public function paste() {
        base.paste();
    }

    vertical-stretch: 0;
    horizontal-stretch: 1;
    min-width: max(Fluent2SizeSettings.input-min-width, layout.min-width);
    min-height: max(Fluent2SizeSettings.control-height, layout.min-height);
    forward-focus: base;

    states [
        disabled when !root.enabled : {
            background.background: Fluent2Palette.control-disabled;
            background.border-color: Fluent2Palette.border;
            base.text-color: Fluent2Palette.text-disabled;
            base.selection-foreground-color: Fluent2Palette.text-accent-foreground-disabled;
            base.placeholder-color: Fluent2Palette.text-disabled;
        }
        focused when root.has-focus : {
            background.background: Fluent2Palette.control-input-active;
            background.border-color: Fluent2Palette.border;
            focus-border.background: Fluent2Palette.accent-background;
            base.placeholder-color: Fluent2Palette.text-tertiary;
        }
    ]

    background := Rectangle {
        border-radius: Fluent2SizeSettings.button-radius;
        background: Fluent2Palette.control-background;
        border-width: Fluent2SizeSettings.stroke-width;
        border-color: Fluent2Palette.text-control-border;

        layout := HorizontalLayout {
            padding-left: Fluent2SizeSettings.control-horizontal-padding;
            padding-right: Fluent2SizeSettings.control-horizontal-padding;

            base := LineEditBase {
                input-type: root.input-type;
                font-size: Fluent2FontSettings.body.font-size;
                font-weight: Fluent2FontSettings.body.font-weight;
                font-family: Fluent2Palette.font-family;
                selection-background-color: Fluent2Palette.selection-background;
                selection-foreground-color: Fluent2Palette.accent-foreground;
                text-color: Fluent2Palette.foreground;
                placeholder-color: Fluent2Palette.text-secondary;
                margin: layout.padding-left + layout.padding-right;
                horizontal-stretch: 1;
            }

            if !root.text.is-empty && root.input-type != InputType.password && root.enabled && !root.read-only && root.has-focus: LineEditClearIcon {
                icon-size: Fluent2SizeSettings.lineedit-icon-size;
                enabled: root.enabled && !root.read-only;
                text: base.text;
                source: @image-url("_dismiss.svg");
                colorize: base.text-color;
                clear => {
                    base.text = "";
                    root.edited("");
                    base.focus();
                }
            }

            if root.input-type == InputType.password && !root.text.is-empty && root.has-focus: LineEditPasswordIcon {
                icon-size: Fluent2SizeSettings.lineedit-icon-size;
                enabled: root.enabled;
                show-password-image: @image-url("_eye_show.svg");
                hide-password-image: @image-url("_eye_hide.svg");
                colorize: base.text-color;
                show-password: base.input-type != InputType.password;
                show-password-changed(show) => {
                    base.input-type = show ? InputType.text : root.input-type;
                    base.focus();
                }
            }
        }

        focus-border := Rectangle {
            x: parent.border-radius;
            y: parent.height - self.height;
            width: parent.width - 2 * parent.border-radius;
            height: Fluent2SizeSettings.input-focus-indicator-height;
        }
    }
}
