// Copyright © SixtyFPS GmbH <info@slint.dev>
// SPDX-License-Identifier: GPL-3.0-only OR LicenseRef-Slint-Royalty-free-2.0 OR LicenseRef-Slint-Software-3.0

import { Fluent2Palette, Fluent2SizeSettings } from "styling.slint";

export component ProgressIndicator {
    in property <float> progress;
    in property <bool> indeterminate;

    min-height: Fluent2SizeSettings.progress-height;
    horizontal-stretch: 1;
    vertical-stretch: 0;
    accessible-role: progress-indicator;
    accessible-value: !root.indeterminate ? root.progress : "";
    accessible-value-minimum: 0.0;
    accessible-value-maximum: 1.0;

    Rectangle {
        clip: true;

        i-rail := Rectangle {
            height: Fluent2SizeSettings.progress-rail-height;
            background: Fluent2Palette.progress-track-background;
            border-radius: Fluent2SizeSettings.progress-rail-radius;
        }

        i-track := Rectangle {
            width: !root.indeterminate ?  parent.width * min(1, max(0, root.progress)) : parent.width;
            height: 100%;
            x: !root.indeterminate ? 0px : -parent.width + (parent.width * mod(animation-tick(), Fluent2SizeSettings.progress-indeterminate-cycle-duration) / Fluent2SizeSettings.progress-indeterminate-sweep-duration);
            border-radius: Fluent2SizeSettings.progress-track-radius;
            background: Fluent2Palette.progress-indicator-active-background;
        }
    }
}
