// Copyright © SixtyFPS GmbH <info@slint.dev>
// SPDX-License-Identifier: GPL-3.0-only OR LicenseRef-Slint-Royalty-free-2.0 OR LicenseRef-Slint-Software-3.0

import { Fluent2Palette, Fluent2SizeSettings, Icons } from "styling.slint";
import { FocusTouchArea } from "internal-components.slint";

component ScrollViewButton {
    in property <image> icon;
    in property <bool> horizontal;
    out property <bool> pressed: touch-area.pressed;
    out property <bool> has-hover: touch-area.has-hover;

    callback clicked <=> touch-area.clicked;

    width: root.horizontal ? Fluent2SizeSettings.scrollbar-button-short-size : Fluent2SizeSettings.scrollbar-button-long-size;
    height: root.horizontal ? Fluent2SizeSettings.scrollbar-button-long-size : Fluent2SizeSettings.scrollbar-button-short-size;

    icon := Image {
        x: (parent.width - self.width) / 2;
        y: (parent.height - self.height) / 2;
        width: parent.width;
        source: root.icon;
        colorize: Fluent2Palette.scrollbar-button-foreground;
        accessible-role: none;

        animate colorize, opacity { duration: Fluent2SizeSettings.scrollbar-motion-duration; }
        animate width, height { duration: Fluent2SizeSettings.scrollbar-motion-duration; easing: ease-out; }
    }

    states [
        pressed when root.pressed : {
            opacity: Fluent2SizeSettings.scrollbar-button-visible-opacity;
            icon.width: root.width - Fluent2SizeSettings.scrollbar-button-pressed-icon-inset;
        }
        hover when root.has-hover : {
            opacity: Fluent2SizeSettings.scrollbar-button-visible-opacity;
            icon.colorize: Fluent2Palette.scrollbar-button-hover-foreground;
        }
    ]

    touch-area := FocusTouchArea {
        enabled: true;
    }
}

component ScrollBar inherits Rectangle {
    in-out property <bool> horizontal;
    in-out property <length> maximum;
    in-out property <length> page-size;
    in-out property <length> value;
    in property <ScrollBarPolicy> policy: ScrollBarPolicy.as-needed;
    in property <bool> enabled;

    callback scrolled();

    property <length> offset: Fluent2SizeSettings.scrollbar-offset;
    property <length> size: Fluent2SizeSettings.scrollbar-collapsed-size;
    property <length> track-size: root.horizontal ? root.width - 2 * root.offset : root.height - 2 * offset;
    property <length> step-size: Fluent2SizeSettings.scrollbar-step-size;

    border-width: Fluent2SizeSettings.scrollbar-track-border-width;
    border-radius: Fluent2SizeSettings.scrollbar-track-radius;
    visible: (self.policy == ScrollBarPolicy.always-on) || (self.policy == ScrollBarPolicy.as-needed && self.maximum > 0);
    clip: true;

    states [
        hover when touch-area.has-hover || down-scroll-button.has-hover || up-scroll-button.has-hover : {
            root.background: Fluent2Palette.scrollbar-track-hover-background;
            root.size: Fluent2SizeSettings.scrollbar-expanded-size;
            up-scroll-button.opacity: Fluent2SizeSettings.scrollbar-button-visible-opacity;
            down-scroll-button.opacity: Fluent2SizeSettings.scrollbar-button-visible-opacity;
        }
    ]

    animate size { duration: Fluent2SizeSettings.scrollbar-motion-duration; easing: ease-out; }

    thumb := Rectangle {
        width: !root.horizontal ? root.size : root.maximum <= 0phx ? Fluent2SizeSettings.scrollbar-zero-range-thumb-size : max(min(Fluent2SizeSettings.scrollbar-min-thumb-size, root.width), root.track-size * root.page-size / (root.maximum + root.page-size));
        height: root.horizontal ? root.size : root.maximum <= 0phx ? Fluent2SizeSettings.scrollbar-zero-range-thumb-size : max(min(Fluent2SizeSettings.scrollbar-min-thumb-size, root.height), root.track-size * (root.page-size / (root.maximum + root.page-size)));
        x: !root.horizontal ? parent.width - Fluent2SizeSettings.scrollbar-button-offset - self.width : root.offset + (root.track-size - thumb.width) * (-root.value / root.maximum);
        y: root.horizontal ? parent.height - Fluent2SizeSettings.scrollbar-button-offset - self.height : root.offset + (root.track-size - thumb.height) * (-root.value / root.maximum);
        border-radius: Fluent2SizeSettings.scrollbar-thumb-radius;
        background: Fluent2Palette.scrollbar-thumb-background;

        animate width, height { duration: Fluent2SizeSettings.scrollbar-motion-duration; easing: ease-out; }
    }

    touch-area := TouchArea {
        property <{pressed-value: length, maximum: length, x:length, y: length}> saved-values;

        width: parent.width;
        height: parent.height;

        function update-saved-values() {
            self.saved-values = { pressed-value: -root.value, maximum: root.maximum, x: self.mouse-x, y: self.mouse-y };
        }

        pointer-event(event) => {
            if (event.button == PointerEventButton.left && event.kind == PointerEventKind.down) {
                self.update-saved-values();
            }
        }

        moved => {
            if (self.enabled && self.pressed) {
                // Update reference points when the size of the viewport changes to
                // avoid 'jumping' during scrolling.
                // This happens when height estimate of a ListView changes after
                // new items are loaded.
                if (self.saved-values.maximum != root.maximum) {
                    self.update-saved-values();
                }

                root.value = -max(0px, min(root.maximum, self.saved-values.pressed-value + (
                    root.horizontal ? (self.mouse-x - self.saved-values.x) * (root.maximum / (root.track-size - thumb.width))
                               : (self.mouse-y - self.saved-values.y) * (root.maximum / (root.track-size - thumb.height))
                )));
                root.scrolled();
            }
        }

        scroll-event(event) => {
            if (root.horizontal && event.delta-x != 0) {
                root.value = max(-root.maximum, min(0px, root.value + event.delta-x));
                return accept;
            } else if (!root.horizontal && event.delta-y != 0) {
                root.value = max(-root.maximum, min(0px, root.value + event.delta-y));
                return accept;
            }
            reject
        }
    }

    up-scroll-button := ScrollViewButton {
        opacity: Fluent2SizeSettings.scrollbar-button-hidden-opacity;
        x: !root.horizontal ? (parent.width - self.width) / 2 : Fluent2SizeSettings.scrollbar-button-offset;
        y: root.horizontal ? (parent.height - self.height) / 2 : Fluent2SizeSettings.scrollbar-button-offset;
        icon: root.horizontal ? Icons.left : Icons.up;
        horizontal: root.horizontal;

        clicked => {
            root.value = min(0px, root.value + root.step-size);
        }
    }

    down-scroll-button := ScrollViewButton {
        opacity: Fluent2SizeSettings.scrollbar-button-hidden-opacity;
        x: !root.horizontal ? (parent.width - self.width) / 2 : root.width - self.width - Fluent2SizeSettings.scrollbar-button-offset;
        y: root.horizontal ? (parent.height - self.height) / 2 : root.height - self.height - Fluent2SizeSettings.scrollbar-button-offset;
        icon: root.horizontal ? Icons.right : Icons.down;
        horizontal: root.horizontal;

        clicked => {
            root.value = max(-root.maximum, root.value - root.step-size);
        }
    }
}

export component ScrollView {
    in property <bool> enabled: true;
    out property <length> visible-width <=> flickable.width;
    out property <length> visible-height <=> flickable.height;
    in-out property <length> viewport-width <=> flickable.viewport-width;
    in-out property <length> viewport-height <=> flickable.viewport-height;
    in-out property <length> viewport-x <=> flickable.viewport-x;
    in-out property <length> viewport-y <=> flickable.viewport-y;
    in property <ScrollBarPolicy> vertical-scrollbar-policy <=> vertical-bar.policy;
    in property <ScrollBarPolicy> horizontal-scrollbar-policy <=> horizontal-bar.policy;
    in property <bool> mouse-drag-pan-enabled <=> flickable.interactive;

    // FIXME: remove. This property is currently set by the ListView and is used by the native style to draw the scrollbar differently when it has focus
    in-out property <bool> has-focus;

    callback scrolled <=> flickable.flicked;

    min-height: Fluent2SizeSettings.scrollview-min-size;
    min-width: Fluent2SizeSettings.scrollview-min-size;
    horizontal-stretch: 1;
    vertical-stretch: 1;
    preferred-height: 100%;
    preferred-width: 100%;

    flickable := Flickable {
        interactive: false;
        viewport-y <=> vertical-bar.value;
        viewport-x <=> horizontal-bar.value;
        width: parent.width;
        height: parent.height;

        @children
    }

    vertical-bar := ScrollBar {
        enabled: root.enabled;
        width: Fluent2SizeSettings.scrollbar-gutter-size;
        x: flickable.width + flickable.x - self.width;
        y: flickable.y;
        height: horizontal-bar.visible ? parent.height - horizontal-bar.height : parent.height;
        horizontal: false;
        maximum:  flickable.viewport-height - flickable.height;
        page-size:  flickable.height;

        scrolled => {root.scrolled()}
    }

    horizontal-bar := ScrollBar {
        enabled: root.enabled;
        width: vertical-bar.visible ? parent.width - vertical-bar.width : parent.width;
        height: Fluent2SizeSettings.scrollbar-gutter-size;
        y: flickable.height + flickable.y - self.height;
        x: flickable.x;
        horizontal: true;
        maximum:  flickable.viewport-width - flickable.width;
        page-size:  flickable.width;

        scrolled => {root.scrolled()}
    }
}
