// Copyright © SixtyFPS GmbH <info@slint.dev>
// SPDX-License-Identifier: GPL-3.0-only OR LicenseRef-Slint-Royalty-free-2.0 OR LicenseRef-Slint-Software-3.0

import { Fluent2FontSettings, Fluent2Palette, Fluent2SizeSettings } from "styling.slint";
import { FocusBorder } from "components.slint";
import { FocusTouchArea } from "internal-components.slint";

export component Switch {
    in property <bool> enabled: true;
    in property <string> text;
    in-out property <bool> checked;
    out property <bool> has-focus: touch-area.has-focus;

    callback toggled;

    private property <color> text-color: Fluent2Palette.switch-foreground;

    function toggle-checked() {
        if(!root.enabled) {
            return;
        }

        root.checked = !root.checked;
        root.toggled();
    }

    min-width: max(Fluent2SizeSettings.switch-width, layout.min-width);
    min-height: max(Fluent2SizeSettings.switch-height, layout.min-height);
    vertical-stretch: 0;
    horizontal-stretch: 0;
    accessible-enabled: root.enabled;
    accessible-label: root.text;
    accessible-checkable: true;
    accessible-checked <=> root.checked;
    accessible-role: switch;
    accessible-action-default => {
        if(root.enabled) {
            root.checked = !root.checked;
            root.toggled();
        }
    }
    forward-focus: touch-area;

    states [
        disabled when !root.enabled : {
            rail.background: root.checked ? Fluent2Palette.switch-rail-checked-disabled-background : Fluent2Palette.switch-rail-disabled-background;
            rail.border-color: Fluent2Palette.switch-rail-disabled-border;
            root.text-color: Fluent2Palette.switch-disabled-foreground;
            thumb.background: root.checked ? Fluent2Palette.switch-thumb-checked-disabled : Fluent2Palette.switch-thumb-disabled;
        }
        pressed when touch-area.pressed : {
            rail.background: root.checked ? Fluent2Palette.switch-rail-checked-pressed-background : Fluent2Palette.switch-rail-pressed-background;
            thumb.width: Fluent2SizeSettings.switch-thumb-pressed-width;
            thumb.height: Fluent2SizeSettings.switch-thumb-pressed-height;
            thumb.border-width: root.checked ? Fluent2SizeSettings.switch-thumb-border-width : Fluent2SizeSettings.control-hidden-stroke-width;
            thumb.background: root.checked ? Fluent2Palette.switch-thumb-checked-pressed-background : Fluent2Palette.switch-thumb-pressed-background;
        }
        hover when touch-area.has-hover : {
            rail.background:  root.checked ? Fluent2Palette.switch-rail-checked-hover-background : Fluent2Palette.switch-rail-hover-background;
            thumb.width: Fluent2SizeSettings.switch-thumb-hover-size;
            thumb.border-width: root.checked ? Fluent2SizeSettings.switch-thumb-border-width : Fluent2SizeSettings.control-hidden-stroke-width;
            thumb.background: root.checked ? Fluent2Palette.switch-thumb-checked-hover-background : Fluent2Palette.switch-thumb-hover-background;
        }
        selected when root.checked : {
            rail.background: Fluent2Palette.switch-rail-checked-background;
            thumb.border-width: Fluent2SizeSettings.switch-thumb-border-width;
            thumb.border-color: Fluent2Palette.switch-thumb-border;
            thumb.background: Fluent2Palette.switch-thumb-checked-background;
        }
    ]

    layout := HorizontalLayout {
        spacing: Fluent2SizeSettings.switch-label-spacing;

        VerticalLayout {
            alignment: center;

           Rectangle {
                width: Fluent2SizeSettings.switch-width;
                height: Fluent2SizeSettings.switch-height;

                rail := Rectangle {
                    border-radius: Fluent2SizeSettings.switch-rail-radius;
                    border-width: root.checked ? Fluent2SizeSettings.control-hidden-stroke-width : Fluent2SizeSettings.switch-rail-border-width;
                    border-color: Fluent2Palette.switch-rail-border;
                    background: Fluent2Palette.switch-rail-background;

                    animate background, border-color { duration: Fluent2SizeSettings.switch-motion-duration; easing: linear; }
                }

                thumb := Rectangle {
                    x: root.checked ? parent.width - self.width - Fluent2SizeSettings.switch-thumb-inset : Fluent2SizeSettings.switch-thumb-inset;
                    y: (parent.height - self.height) / 2;
                    width: Fluent2SizeSettings.switch-thumb-size;
                    height: self.width;
                    border-radius: Fluent2SizeSettings.switch-thumb-radius;
                    background: Fluent2Palette.switch-thumb-background;
                    border-color: Fluent2Palette.switch-thumb-border;

                    animate background, border-color, border-width, x, y, width, height { duration: Fluent2SizeSettings.switch-motion-duration; easing: linear; }
                }

                // focus border
                if root.has-focus && root.enabled : FocusBorder {
                    border-radius: rail.border-radius;
                }
            }
        }

        if (root.text != "") : Text {
            text: root.text;
            color: root.text-color;
            font-size: Fluent2FontSettings.body.font-size;
            font-weight: Fluent2FontSettings.body.font-weight;
            font-family: Fluent2Palette.font-family;
            vertical-alignment: center;
            horizontal-alignment: left;
        }
    }

    touch-area := FocusTouchArea {
        enabled: root.enabled;

        clicked => {
            root.toggle-checked();
        }
    }
}
