// Copyright © SixtyFPS GmbH <info@slint.dev>
// SPDX-License-Identifier: GPL-3.0-only OR LicenseRef-Slint-Royalty-free-2.0 OR LicenseRef-Slint-Software-3.0

import { Fluent2FontSettings, Fluent2Palette, Fluent2SizeSettings } from "styling.slint";
import { FocusBorder } from "components.slint";
import { FocusTouchArea } from "internal-components.slint";

export component Switch {
    in property <bool> enabled: true;
    in property <string> text;
    in-out property <bool> checked;
    out property <bool> has-focus: touch-area.has-focus;

    callback toggled;

    private property <color> text-color: Fluent2Palette.foreground;

    function toggle-checked() {
        if(!root.enabled) {
            return;
        }

        root.checked = !root.checked;
        root.toggled();
    }

    min-width: max(Fluent2SizeSettings.switch-width, layout.min-width);
    min-height: max(Fluent2SizeSettings.switch-height, layout.min-height);
    vertical-stretch: 0;
    horizontal-stretch: 0;
    accessible-enabled: root.enabled;
    accessible-label: root.text;
    accessible-checkable: true;
    accessible-checked <=> root.checked;
    accessible-role: switch;
    accessible-action-default => {
        if(root.enabled) {
            root.checked = !root.checked;
            root.toggled();
        }
    }
    forward-focus: touch-area;

    states [
        disabled when !root.enabled : {
            rail.background: root.checked ? Fluent2Palette.accent-disabled : transparent;
            rail.border-color: Fluent2Palette.control-strong-stroke-disabled;
            root.text-color: Fluent2Palette.text-disabled;
            thumb.background: root.checked ? Fluent2Palette.switch-thumb-checked-disabled : Fluent2Palette.switch-thumb-disabled;
        }
        pressed when touch-area.pressed : {
            rail.background: root.checked ? Fluent2Palette.tertiary-accent-background : Fluent2Palette.control-alt-quartiary;
            thumb.width: Fluent2SizeSettings.switch-thumb-pressed-width;
            thumb.height: Fluent2SizeSettings.switch-thumb-pressed-height;
            thumb.border-width: root.checked ? Fluent2SizeSettings.stroke-width : Fluent2SizeSettings.control-hidden-stroke-width;
            thumb.background: root.checked ? Fluent2Palette.accent-foreground : Fluent2Palette.text-secondary;
        }
        hover when touch-area.has-hover : {
            rail.background:  root.checked ? Fluent2Palette.secondary-accent-background : Fluent2Palette.control-alt-tertiary;
            thumb.width: Fluent2SizeSettings.switch-thumb-hover-size;
            thumb.border-width: root.checked ? Fluent2SizeSettings.stroke-width : Fluent2SizeSettings.control-hidden-stroke-width;
            thumb.background: root.checked ? Fluent2Palette.accent-foreground : Fluent2Palette.text-secondary;
        }
        selected when root.checked : {
            rail.background: Fluent2Palette.accent-background;
            thumb.border-width: Fluent2SizeSettings.stroke-width;
            thumb.border-color: Fluent2Palette.circle-border;
            thumb.background: Fluent2Palette.accent-foreground;
        }
    ]

    layout := HorizontalLayout {
        spacing: Fluent2SizeSettings.control-label-spacing;

        VerticalLayout {
            alignment: center;

           Rectangle {
                width: Fluent2SizeSettings.switch-width;
                height: Fluent2SizeSettings.switch-height;

                rail := Rectangle {
                    border-radius: self.height / 2;
                    border-width: root.checked ? Fluent2SizeSettings.control-hidden-stroke-width : Fluent2SizeSettings.stroke-width;
                    border-color: Fluent2Palette.control-strong-stroke;
                    background: Fluent2Palette.control-alt-secondary;
                }

                thumb := Rectangle {
                    x: root.checked ? parent.width - self.width - Fluent2SizeSettings.switch-thumb-inset : Fluent2SizeSettings.switch-thumb-inset;
                    y: (parent.height - self.height) / 2;
                    width: Fluent2SizeSettings.switch-thumb-size;
                    height: self.width;
                    border-radius: self.height / 2;
                    background: Fluent2Palette.text-secondary;
                    border-color: Fluent2Palette.circle-border;

                    animate background, width { duration: Fluent2SizeSettings.control-motion-duration; easing: linear; }
                }

                // focus border
                if root.has-focus && root.enabled : FocusBorder {
                    border-radius: rail.border-radius;
                }
            }
        }

        if (root.text != "") : Text {
            text: root.text;
            color: root.text-color;
            font-size: Fluent2FontSettings.body.font-size;
            font-weight: Fluent2FontSettings.body.font-weight;
            font-family: Fluent2Palette.font-family;
            vertical-alignment: center;
            horizontal-alignment: left;
        }
    }

    touch-area := FocusTouchArea {
        enabled: root.enabled;

        clicked => {
            root.toggle-checked();
        }
    }
}
