// Copyright © SixtyFPS GmbH <info@slint.dev>
// SPDX-License-Identifier: GPL-3.0-only OR LicenseRef-Slint-Royalty-free-2.0 OR LicenseRef-Slint-Software-3.0

import { Fluent2Palette, Fluent2FontSettings, Fluent2SizeSettings } from "styling.slint";
import { FocusBorder } from "components.slint";
import { FocusTouchArea } from "internal-components.slint";
import { TabBarBase } from "tabwidget-base.slint";

export component TabWidgetImpl inherits Rectangle {
    in property <length> tabbar-preferred-height;
    in property <length> tabbar-preferred-width;
    in property <length> content-min-height;
    in property <length> content-min-width;
    in property <int> current-index;
    in property <int> current-focused;
    in property <Orientation> orientation:Orientation.horizontal;
    out property <length> content-x: orientation == Orientation.horizontal ? 0 : root.tabbar-preferred-width;
    out property <length> content-y: orientation == Orientation.horizontal ? root.tabbar-preferred-height : 0;
    out property <length> content-height:orientation == Orientation.horizontal ? root.height - root.tabbar-preferred-height : root.height;
    out property <length> content-width: orientation == Orientation.horizontal ? root.width : root.width - root.tabbar-preferred-width;
    out property <length> tabbar-x: 0;
    out property <length> tabbar-y: 0;
    out property <length> tabbar-height: orientation == Orientation.horizontal ? root.tabbar-preferred-height : root.height;
    out property <length> tabbar-width: orientation == Orientation.horizontal ? root.width : root.tabbar-preferred-width;
    preferred-width: root.content-min-width;
    min-width: max(root.content-min-width, root.tabbar-preferred-width);
    preferred-height: root.content-min-height + root.tabbar-preferred-height;
    min-height: root.content-min-height + root.tabbar-preferred-height;
}

export component TabImpl inherits Rectangle {
    // The currently focused tab
    in property <int> current-focused;
    // The index of this tab
    in property <int> tab-index;
    // The total number of tabs
    in property <int> num-tabs;
    in property <string> title <=> i-text.text;
    in property <bool> enabled: true;
    out property <bool> has-focus: root.current-focused == root.tab-index || i-touch-area.has-focus;
    // The currently selected tab
    in-out property <int> current;
    private property <bool> hide-right-border: root.tab-index == root.num-tabs - 1 || tab-index + 1 == current;
    private property <bool> is-current: root.tab-index == root.current;
    min-width: max(Fluent2SizeSettings.tab-min-width, i-text.min-width);
    min-height: max(Fluent2SizeSettings.tab-height, i-text.min-height);
    horizontal-stretch: 0;
    vertical-stretch: 0;
    accessible-role: tab;
    accessible-enabled: root.enabled;
    accessible-label: root.title;
    accessible-item-index: root.tab-index;
    accessible-item-selectable: true;
    accessible-item-selected: root.is-current;
    accessible-action-default => {
        i-touch-area.clicked();
    }
    forward-focus: i-touch-area;
    Rectangle {
        clip: true;
        width: 100%;
        height: 100%;
        i-background := Rectangle {
            y: Fluent2SizeSettings.tab-border-width;
            width: 100%;
            height: parent.height + self.border-radius;
            border-radius: Fluent2SizeSettings.tab-radius;
            border-width: root.is-current ? Fluent2SizeSettings.tab-border-width : Fluent2SizeSettings.control-hidden-stroke-width;
            border-color: Fluent2Palette.tab-border;
            background: i-touch-area.pressed ? Fluent2Palette.tab-pressed-background : root.is-current ? Fluent2Palette.tab-selected-background : i-touch-area.has-hover ? Fluent2Palette.tab-hover-background : Fluent2Palette.tab-background;
        }
    }

    i-touch-area := FocusTouchArea {
        enabled <=> root.enabled;
        clicked => {
            root.current = root.tab-index;
        }
    }

    i-layout := HorizontalLayout {
        padding-left: Fluent2SizeSettings.tab-horizontal-padding;
        padding-right: Fluent2SizeSettings.tab-horizontal-padding;
        i-text := Text {
            vertical-alignment: center;
            horizontal-alignment: left;
            font-size: root.is-current ? Fluent2FontSettings.body-strong.font-size : Fluent2FontSettings.body.font-size;
            font-weight: root.is-current ? Fluent2FontSettings.body-strong.font-weight : Fluent2FontSettings.body.font-weight;
            font-family: Fluent2Palette.font-family;
            color: root.is-current ? Fluent2Palette.tab-selected-foreground : Fluent2Palette.tab-foreground;
            accessible-role: none;
        }
    }

    if (!root.is-current && !root.hide-right-border && !i-touch-area.has-hover && !i-touch-area.pressed): Rectangle {
        x: (parent.width - self.width);
        width: Fluent2SizeSettings.tab-separator-thickness;
        height: Fluent2SizeSettings.selection-indicator-height;
        background: Fluent2Palette.tab-separator;
    }
    if (!root.is-current && !i-touch-area.has-hover && !i-touch-area.pressed): Rectangle {
        y: (parent.height - self.height);
        width: 100%;
        height: Fluent2SizeSettings.tab-separator-thickness;
        background: Fluent2Palette.tab-separator;
    }

    // focus border
    if (root.has-focus && root.enabled): FocusBorder {
        border-radius: i-background.border-radius;
    }
}

component FluentTabBarBase inherits TabBarBase {
    // injected properties:
    // The currently focused tab
    in-out property <int> current-focused: i-focus-scope.has-focus ? i-focus-scope.focused-tab : -1;
    accessible-role: tab-list;
    accessible-delegate-focus: root.current-focused >= 0 ? root.current-focused : root.current;
    accessible-item-count: root.num-tabs;
    i-focus-scope := FocusScope {
        property <int> focused-tab: 0;
        x: 0;
        // Do not react on clicks
        width: Fluent2SizeSettings.interaction-receiver-size;
        key-pressed(event) => {
            if (event.text == "\n") {
                root.current = root.current-focused;
                return accept;
            }
            if (event.text == Key.LeftArrow) {
                self.focused-tab = Math.max(self.focused-tab - 1,  0);
                return accept;
            }
            if (event.text == Key.RightArrow) {
                self.focused-tab = Math.min(self.focused-tab + 1, root.num-tabs - 1);
                return accept;
            }
            return reject;
        }
        key-released(event) => {
            if (event.text == " ") {
                root.current = root.current-focused;
                return accept;
            }
            return reject;
        }
    }
}

export component TabBarHorizontalImpl inherits FluentTabBarBase {
    Flickable {
        HorizontalLayout {
            @children
        }
    }
}

export component TabBarVerticalImpl inherits FluentTabBarBase {
    Flickable {
        VerticalLayout {
            @children
        }
    }
}

export component TabBarImpl inherits TabBarBase { }

export component TabWidget inherits TabWidget { }
