// Copyright © SixtyFPS GmbH <info@slint.dev>
// SPDX-License-Identifier: GPL-3.0-only OR LicenseRef-Slint-Royalty-free-2.0 OR LicenseRef-Slint-Software-3.0

import { Fluent2FontSettings, Fluent2Palette, Fluent2SizeSettings } from "styling.slint";
import { ScrollView } from "scrollview.slint";
import { TextEditBase } from "textedit-base.slint";

export component TextEdit {
    in property <TextWrap> wrap <=> base.wrap;
    in property <TextHorizontalAlignment> horizontal-alignment <=> base.horizontal-alignment;
    in property <bool> read-only <=> base.read-only;
    in property <length> font-size <=> base.font-size;
    in property <string> font-family <=> base.font-family;
    in property <bool> font-italic <=> base.font-italic;
    in property <bool> enabled <=> base.enabled;
    in property <string> placeholder-text <=> base.placeholder-text;
    out property <bool> has-focus: base.has-focus;
    out property <length> visible-width <=> base.visible-width;
    out property <length> visible-height <=> base.visible-height;
    in-out property <string> text <=> base.text;
    in-out property <length> viewport-x <=> base.viewport-x;
    in-out property <length> viewport-y <=> base.viewport-y;
    in-out property <length> viewport-width <=> base.viewport-width;
    in-out property <length> viewport-height <=> base.viewport-height;

    callback edited <=> base.edited;
    callback key-pressed <=> base.key-pressed;
    callback key-released <=> base.key-released;

    accessible-role: AccessibleRole.text-input;
    accessible-enabled: root.enabled;
    accessible-value <=> text;
    accessible-placeholder-text: placeholder-text;
    accessible-read-only: root.read-only;

    public function set-selection-offsets(start: int, end: int) {
        base.set-selection-offsets(start, end);
    }

    public function select-all() {
        base.select-all();
    }

    public function clear-selection() {
        base.clear-selection();
    }

    public function cut() {
        base.cut();
    }

    public function copy() {
        base.copy();
    }

    public function paste() {
        base.paste();
    }

    forward-focus: base;
    horizontal-stretch: 1;
    vertical-stretch: 1;

    states [
        disabled when !root.enabled: {
            base.background: Fluent2Palette.text-input-disabled-background;
            base.border-color: Fluent2Palette.text-input-disabled-border;
            base.foreground: Fluent2Palette.text-input-disabled-foreground;
            base.selection-foreground-color: Fluent2Palette.text-input-disabled-selection-foreground;
        }
        focused when root.has-focus: {
            base.background: Fluent2Palette.text-input-active-background;
            base.border-color: Fluent2Palette.text-control-border;
            i-focus-border.background: Fluent2Palette.text-input-focus-indicator-background;
        }
    ]

    base := TextEditBase {
        width: 100%;
        height: 100%;
        background: Fluent2Palette.text-input-background;
        border-radius: Fluent2SizeSettings.button-radius;
        border-width: Fluent2SizeSettings.stroke-width;
        border-color: Fluent2Palette.text-control-border;
        scroll-view-padding: Fluent2SizeSettings.control-horizontal-padding;
        cursor-margin: Fluent2SizeSettings.control-horizontal-padding;
        estimated-line-height: Fluent2SizeSettings.textedit-estimated-line-height;
        foreground: Fluent2Palette.text-input-foreground;
        font-size: Fluent2FontSettings.body.font-size;
        font-weight: Fluent2FontSettings.body.font-weight;
        font-family: Fluent2Palette.font-family;
        placeholder-color: Fluent2Palette.text-input-placeholder-foreground;
        selection-background-color: Fluent2Palette.text-input-selection-background;
        selection-foreground-color: Fluent2Palette.text-input-selection-foreground;

        i-focus-border := Rectangle {
            x: parent.border-radius;
            y: parent.height - self.height;
            width: parent.width - 2 * parent.border-radius;
            height: Fluent2SizeSettings.input-focus-indicator-height;
        }
    }
}
