// Copyright © SixtyFPS GmbH <info@slint.dev>
// SPDX-License-Identifier: GPL-3.0-only OR LicenseRef-Slint-Royalty-free-2.0 OR LicenseRef-Slint-Software-3.0

import { RetroToneFontSettings, RetroTonePalette, Icons } from "styling.slint";
import { FocusBorder } from "components.slint";

export component CheckBox {
    in property <string> text;
    in property <bool> enabled <=> touch-area.enabled;
    out property <bool> has-focus: focus-scope.has-focus;
    in-out property <bool> checked;

    callback toggled;

    private property <color> text-color: RetroTonePalette.foreground;

    min-height: max(18px, layout.min-height);
    accessible-checkable: true;
    accessible-enabled: root.enabled;
    accessible-label: root.text;
    accessible-checked <=> root.checked;
    accessible-role: checkbox;
    accessible-action-default => {
        if (root.enabled) {
           root.checked = !root.checked;
           root.toggled();
        }
    }
    forward-focus: focus-scope;

    states [
        disabled when !root.enabled : {
            border.border-color: RetroTonePalette.control-strong-stroke-disabled;
            background.background: root.checked ? RetroTonePalette.accent-disabled : RetroTonePalette.control-alt-disabled;
            icon.colorize: RetroTonePalette.text-accent-foreground-disabled;
            root.text-color: RetroTonePalette.text-disabled;
        }
        pressed when touch-area.pressed : {
            border.border-color: RetroTonePalette.control-strong-stroke-disabled;
            background.background: root.checked ? RetroTonePalette.tertiary-accent-background : RetroTonePalette.control-alt-quartiary;
            icon.colorize: RetroTonePalette.text-accent-foreground-secondary;
        }
        hover when touch-area.has-hover : {
            background.background: root.checked ?  RetroTonePalette.secondary-accent-background : RetroTonePalette.control-alt-tertiary;
        }
        checked when root.checked && root.enabled : {
            background.background: RetroTonePalette.accent-background;
        }
    ]

    layout := HorizontalLayout {
        spacing: 12px;

        background := Rectangle {
            width: 18px;
            height: self.width;
            y: (parent.height - self.height) / 2;
            background: RetroTonePalette.control-alt-secondary;
            border-radius: 0px;

            border := Rectangle {
                border-color: RetroTonePalette.control-strong-stroke;
                border-width: root.checked ? 0 : 1px;
                border-radius: parent.border-radius;
            }

            icon := Image {
                image-fit: contain;
                visible: root.checked;
                source: Icons.check-mark;
                colorize: RetroTonePalette.accent-foreground;
                width: 12px;
                accessible-role: none;
            }
        }

        if root.text != "" : Text {
            text: root.text;
            color: root.text-color;
            font-size: RetroToneFontSettings.body.font-size;
            font-weight: RetroToneFontSettings.body.font-weight;
            vertical-alignment: center;
            horizontal-alignment: left;
        }
    }

    touch-area := TouchArea {
        clicked => {
            if (root.enabled) {
                root.checked = !root.checked;
                root.toggled();
            }
        }
    }

    focus-scope := FocusScope {
        x: 0;
        width: 0; // Do not react on clicks
        enabled <=> root.enabled;

        key-pressed(event) => {
            if (event.text == " " || event.text == "\n") {
                touch-area.clicked();
                return accept;
            }
            return reject;
        }
    }

    // focus border
    if root.has-focus && root.enabled : FocusBorder {
        border-radius: 0px;
    }
}
