// Copyright © SixtyFPS GmbH <info@slint.dev>
// SPDX-License-Identifier: GPL-3.0-only OR LicenseRef-Slint-Royalty-free-2.0 OR LicenseRef-Slint-Software-3.0

import { RetroTonePalette, RetroToneFontSettings, RetroToneSizeSettings } from "styling.slint";

export component FocusBorder inherits Rectangle {
    border-width: 3px;
    border-color: RetroTonePalette.focus-stroke-outer;

    Rectangle {
        x: parent.border-width;
        y: parent.border-width;
        width: parent.width - 2 * parent.border-width;
        height: parent.height - 2 * parent.border-width;
        border-width: 2px;
        border-radius: parent.border-radius - 2px;
        border-color: RetroTonePalette.focus-stroke-inner;
    }
}

export component MenuBorder inherits Rectangle {
    border-radius: 0px;
    background: RetroTonePalette.alternate-background;

    Rectangle {
        border-width: 2px;
        border-radius: parent.border-radius;
        border-color: RetroTonePalette.control-background-stroke-flyout;
    }
}

export component ListItem {
    in property <bool> is-selected;
    in property <StandardListViewItem> item;
    in property <bool> has-focus;
    in property <bool> has-hover;
    in property <bool> pressed;
    in property <int> index;
    in property <length> pressed-x;
    in property <length> pressed-y;

    min-width: i-layout.min-width;
    min-height: max(RetroToneSizeSettings.item-height, i-layout.min-height);
    vertical-stretch: 0;
    horizontal-stretch: 1;
    accessible-role: list-item;
    accessible-label: root.item.text;
    accessible-item-selectable: true;
    accessible-item-selected: root.is-selected;
    accessible-item-index: root.index;

    states [
        pressed when root.pressed : {
            i-background.background: is-selected ? RetroTonePalette.subtle-secondary : RetroTonePalette.subtle-tertiary;
        }
        hover when root.has-hover : {
            i-text.color: RetroTonePalette.text-secondary;
            i-background.background: is-selected ? RetroTonePalette.subtle-tertiary : RetroTonePalette.subtle-secondary;
            i-selector.height: root.is-selected ? 16px : 0;
        }
        is-selected when root.is-selected : {
            i-background.background: RetroTonePalette.subtle-secondary;
            i-selector.height: 16px;
        }
    ]

    if (root.has-focus) : FocusBorder {
        border-radius: 0px;
    }

    i-background := Rectangle {
        width: root.width - 6px;
        height: root.height - 4px;
        background: transparent;
        border-radius: 0px;

        i-layout := HorizontalLayout {
            padding-left: 16px;
            padding-right: 16px;
            spacing: 4px;

            i-text := Text {
                text: root.item.text;
                color: RetroTonePalette.control-foreground;
                font-size: RetroToneFontSettings.body.font-size;
                font-weight: RetroToneFontSettings.body.font-weight;
                vertical-alignment: center;
                horizontal-alignment: left;
                overflow: elide;
                accessible-role: none;
            }
        }

        i-selector := Rectangle {
            x: 0px;
            y: (parent.height - self.height) / 2;
            width: 3px;
            height: 0px;
            background: RetroTonePalette.accent-background;
            border-radius: 0px;
        }
    }

    @children
}
