// Copyright © SixtyFPS GmbH <info@slint.dev>
// SPDX-License-Identifier: GPL-3.0-only OR LicenseRef-Slint-Royalty-free-2.0 OR LicenseRef-Slint-Software-3.0

import { RetroTonePalette, RetroToneFontSettings, Icons } from "styling.slint";
import { SpinBoxBase } from "../common/spinbox-base.slint";

component SpinBoxButton {
    callback clicked <=> touch-area.clicked;

    in property <image> icon <=> icon.source;

    min-width: 28px;
    horizontal-stretch: 0;

    states [
        pressed when touch-area.pressed : {
            background.background: RetroTonePalette.subtle;
        }
    ]

    background := Rectangle {
        border-radius: 0px;

        icon := Image {
            image-fit: contain;
            colorize: RetroTonePalette.text-secondary;
            width: 12px;
            accessible-role: none;
        }
    }

    touch-area := TouchArea {}
}

export component SpinBox {
    in property <int> minimum <=> base.minimum;
    in property <int> maximum <=> base.maximum;
    in property <bool> enabled <=> base.enabled;
    in property <int> step-size <=> base.step-size;
    in property <bool> read-only <=> base.read-only;
    in property <TextHorizontalAlignment> horizontal-alignment <=> base.horizontal-alignment;
    out property <bool> has-focus <=> base.has-focus;
    in-out property <int> value <=> base.value;

    callback edited <=> base.edited;

    min-width: max(128px, layout.min-width);
    min-height: max(30px, layout.min-height);
    vertical-stretch: 0;
    horizontal-stretch: 1;
    forward-focus: base;

    accessible-role: spinbox;
    accessible-enabled: root.enabled;
    accessible-value: root.value;
    accessible-value-minimum: root.minimum;
    accessible-value-maximum: root.maximum;
    accessible-value-step: (root.maximum - root.minimum) / 100;
    accessible-action-set-value(v) => { if v.is-float() { base.update-value(v.to-float()); } }
    accessible-action-increment => { base.increment(); }
    accessible-action-decrement => { base.decrement(); }
    accessible-read-only: root.read-only;

    states [
        disabled when !root.enabled : {
            background.background: RetroTonePalette.control-disabled;
            background.border-color: RetroTonePalette.border;
            base.color: RetroTonePalette.text-disabled;
            base.selection-foreground-color: RetroTonePalette.text-accent-foreground-disabled;
        }
        focused when root.has-focus : {
            background.background: RetroTonePalette.control-input-active;
            background.border-color: RetroTonePalette.border;
            focus-border.background: RetroTonePalette.accent-background;
        }
    ]

    background := Rectangle {
        border-radius: 0px;
        background: RetroTonePalette.control-background;
        border-width: 2px;
        border-color: RetroTonePalette.text-control-border;

        layout := HorizontalLayout {
            padding-left: 12px;
            padding-right: 2px;
            padding-top: 4px;
            padding-bottom: 4px;
            spacing: 4px;

            Rectangle {
                clip: true;
                horizontal-stretch: 1;

                base := SpinBoxBase {
                    width: 100%;
                    color: RetroTonePalette.control-foreground;
                    font-size: RetroToneFontSettings.body.font-size;
                    font-weight: RetroToneFontSettings.body.font-weight;
                    selection-background-color: RetroTonePalette.selection-background;
                    selection-foreground-color: RetroTonePalette.accent-foreground;
                }
            }

            SpinBoxButton {
                visible: root.enabled && !root.read-only;
                icon: Icons.chevron-up;

                clicked => {
                    base.increment();
                }
            }

            SpinBoxButton {
                visible: root.enabled && !root.read-only;
                icon: Icons.chevron-down;

                clicked => {
                    base.decrement();
                }
            }
        }

        focus-border := Rectangle {
            x: parent.border-radius;
            y: parent.height - self.height;
            width: parent.width - 2 * parent.border-radius;
            height: 2px;
        }
    }
}
