// Copyright © SixtyFPS GmbH <info@slint.dev>
// SPDX-License-Identifier: GPL-3.0-only OR LicenseRef-Slint-Royalty-free-2.0 OR LicenseRef-Slint-Software-3.0

import { RetroToneFontSettings, RetroTonePalette } from "styling.slint";
import { FocusBorder } from "components.slint";

export component Switch {
    in property <bool> enabled: true;
    in property <string> text;
    in-out property <bool> checked;
    out property <bool> has-focus: focus-scope.has-focus;

    callback toggled;

    private property <color> text-color: RetroTonePalette.foreground;

    function toggle-checked() {
        if(!root.enabled) {
            return;
        }

        root.checked = !root.checked;
        root.toggled();
    }

    min-width: max(40px, layout.min-width);
    min-height: max(20px, layout.min-height);
    vertical-stretch: 0;
    horizontal-stretch: 0;
    accessible-enabled: root.enabled;
    accessible-label: root.text;
    accessible-checkable: true;
    accessible-checked <=> root.checked;
    accessible-role: switch;
    accessible-action-default => {
        if(root.enabled) {
            root.checked = !root.checked;
            root.toggled();
        }
    }
    forward-focus: focus-scope;

    states [
        disabled when !root.enabled : {
            rail.border-color: RetroTonePalette.control-strong-stroke-disabled;
            thumb.background: RetroTonePalette.text-disabled;
            root.text-color: RetroTonePalette.text-disabled;
        }
        pressed when touch-area.pressed : {
            thumb.background: root.checked ? RetroTonePalette.accent-background : RetroTonePalette.text-secondary;
        }
        hover when touch-area.has-hover : {
            rail.border-color: RetroTonePalette.accent-background;
            thumb.background: root.checked ? RetroTonePalette.accent-background : RetroTonePalette.text-secondary;
        }
        selected when root.checked : {
            rail.border-color: RetroTonePalette.accent-background;
            thumb.background: RetroTonePalette.accent-background;
        }
    ]

    layout := HorizontalLayout {
        spacing: 12px;

        VerticalLayout {
            alignment: center;

           Rectangle {
                width: 40px;
                height: 16px;

                rail := Rectangle {
                    border-width: 1px;
                    border-color: RetroTonePalette.control-strong-stroke;
                    background: transparent;
                }

                thumb := Rectangle {
                    x: root.checked ? parent.width - self.width - 1px : 1px;
                    y: (parent.height - self.height) / 2;
                    width: 14px;
                    height: 14px;
                    background: RetroTonePalette.text-secondary;
                }

                if root.has-focus && root.enabled : FocusBorder {
                    border-radius: 0px;
                }
            }
        }

        if (root.text != "") : Text {
            text: root.text;
            color: root.text-color;
            font-size: RetroToneFontSettings.body.font-size;
            font-weight: RetroToneFontSettings.body.font-weight;
            vertical-alignment: center;
            horizontal-alignment: left;
        }
    }

    touch-area := TouchArea {
        enabled <=> root.enabled;

        clicked => {
            root.toggle-checked();
        }
    }

    focus-scope := FocusScope {
        x:0;
        width: 0px;
        enabled <=> root.enabled;

        key-pressed(event) => {
            if (event.text == " " || event.text == "\n") {
                 root.toggle-checked();
                 return accept;
            }
            return reject;
        }
    }
}
