// Copyright © SixtyFPS GmbH <info@slint.dev>
// SPDX-License-Identifier: GPL-3.0-only OR LicenseRef-Slint-Royalty-free-2.0 OR LicenseRef-Slint-Software-3.0

import { RetroToneFontSettings, RetroTonePalette } from "styling.slint";
import { ScrollView } from "scrollview.slint";
import { TextEditBase } from "../common/textedit-base.slint";

export component TextEdit {
    in property <TextWrap> wrap <=> base.wrap;
    in property <TextHorizontalAlignment> horizontal-alignment <=> base.horizontal-alignment;
    in property <bool> read-only <=> base.read-only;
    in property <length> font-size <=> base.font-size;
    in property <string> font-family <=> base.font-family;
    in property <bool> font-italic <=> base.font-italic;
    in property <bool> enabled <=> base.enabled;
    in property <string> placeholder-text <=> base.placeholder-text;
    out property <bool> has-focus: base.has-focus;
    out property <length> visible-width <=> base.visible-width;
    out property <length> visible-height <=> base.visible-height;
    in-out property <string> text <=> base.text;
    in-out property <length> viewport-x <=> base.viewport-x;
    in-out property <length> viewport-y <=> base.viewport-y;
    in-out property <length> viewport-width <=> base.viewport-width;
    in-out property <length> viewport-height <=> base.viewport-height;

    callback edited <=> base.edited;
    callback key-pressed <=> base.key-pressed;
    callback key-released <=> base.key-released;

    accessible-role: AccessibleRole.text-input;
    accessible-enabled: root.enabled;
    accessible-value <=> text;
    accessible-placeholder-text: placeholder-text;
    accessible-read-only: root.read-only;

    public function set-selection-offsets(start: int, end: int) {
        base.set-selection-offsets(start, end);
    }

    public function select-all() {
        base.select-all();
    }

    public function clear-selection() {
        base.clear-selection();
    }

    public function cut() {
        base.cut();
    }

    public function copy() {
        base.copy();
    }

    public function paste() {
        base.paste();
    }

    forward-focus: base;
    horizontal-stretch: 1;
    vertical-stretch: 1;

    states [
        disabled when !root.enabled: {
            base.foreground: RetroTonePalette.text-disabled;
            base.selection-foreground-color: RetroTonePalette.text-accent-foreground-disabled;
            i-focus-border.background: RetroTonePalette.control-strong-stroke-disabled;
        }
        focused when root.has-focus: {
            i-focus-border.background: RetroTonePalette.accent-background;
            i-focus-border.height: 2px;
        }
    ]

    base := TextEditBase {
        width: 100%;
        height: 100%;
        background: transparent;
        border-radius: 0px;
        border-width: 0px;
        scroll-view-padding: 8px;
        foreground: RetroTonePalette.foreground;
        font-size: RetroToneFontSettings.body.font-size;
        font-weight: RetroToneFontSettings.body.font-weight;
        placeholder-color: RetroTonePalette.text-secondary;
        selection-background-color: RetroTonePalette.selection-background;
        selection-foreground-color: RetroTonePalette.selection-foreground;

        i-focus-border := Rectangle {
            x: 0;
            y: parent.height - self.height;
            width: parent.width;
            height: 1px;
            background: RetroTonePalette.border;
        }
    }
}
